### ISSUE TITLE
Notification to show progress

### ISSUE THREAD

**Issue by Sudhanshhu** [abdallah-odeh/flutter_file_downloader#13]
how can we display progress and can make it openable when click on it.

**Comment by abdallah-odeh** [comment]
Currently it shows a progress notification, 
Disabling the notification or showing complete notification will be implemented soon.

try to download a large or medium size file, [this pdf for example](https://research.nhm.org/pdfs/10840/10840-002.pdf) (14MB),
if the app does not display progress notification please refer to [think solution](https://stackoverflow.com/a/43841708) and try solution 1

**Comment by abdallah-odeh** [comment]
Hello @Sudhanshhu,
the feature of controlling the notification now implemented in the version [flutter_file_downloader: ^1.1.3-dev.4](https://pub.dev/packages/flutter_file_downloader/versions/1.1.3-dev.4)

Please test it in your use case and let me know the results,
note that if you want to disable the notifications completely you must add the permission `<uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />` to your `AndroidManifest.xml` file

**Comment by abdallah-odeh** [comment]
Closing this issue assuming everything works fine, will be merging the prerelease to production this week.
Please if you face any issue with this feature reopen the issue & I'll be glad to help.

Thank you for making this plugin better.
