### ISSUE TITLE
Download cancel

### ISSUE THREAD

**Issue by xdamien7** [abdallah-odeh/flutter_file_downloader#14]
Hello,

If my app is downloading **multiple** files, how do I stop the download process when
the user wants to cancel downloading.

**Comment by abdallah-odeh** [comment]
Hello @xdamien7,
apologize for the late response, this feature is now implemented on prerelease version `flutter_file_downloader: ^1.2.0-dev.4`
please take sometime to test it out on your use case and let me know if fits your needs

thank you for helping in improving this plugin

**Comment by abdallah-odeh** [comment]
Hello @xdamien7,
I just wanted to inform you that this feature has been released to production in version `flutter_file_downloader: ^1.2.0`
your feedback is highly appreciated, if you face any related issue please don't hesitate in reopening this issue.
thank you for making this plugin better
