### ISSUE TITLE
Support for passing custom headers for the download request

### ISSUE THREAD

**Issue by vermavashish** [abdallah-odeh/flutter_file_downloader#16]

**Comment by abdallah-odeh** [comment]
Hello @vermavashish,

Apologize for the delay of publishing this feature.

This feature is now available in **prerelease** version.
please test it out on your use case on the version `flutter_file_downloader: ^1.2.0-dev.1`

thank you for helping in making this plugin better

**Comment by abdallah-odeh** [comment]
Hello @vermavashish,
I will be publishing this feature on production this weekend,
so please consider taking so time testing it on your use case, to see if your requirements are met

thanks in advance.

**Comment by abdallah-odeh** [comment]
It's available only in preproduction release
`flutter_file_downloader: ^1.2.0-dev.1`
I didn't have time to release it to production but I will do so soon & I will reply to this issue when it's released
Please use the mentioned version on your use case and let me know if you have anything

**Comment by abdallah-odeh** [comment]
Hello @facundoduran & @vermavashish ,
I just wanted to inform you guys that this feature has been released to production in version `flutter_file_downloader: ^1.2.0`
your feedback is highly appreciated, if you face any related issue please don't hesitate in reopening this issue.
thank you for making this plugin better
