### ISSUE TITLE
download error crash

### ISSUE THREAD

**Issue by coderXiezhiheng** [abdallah-odeh/flutter_file_downloader#17]
CrashReport( 3304): java.lang.ArithmeticException rid:75ab4ed7-9f18-4126-ade4-a42d6dbb00b2 sess:0fae1c08-6b7a-461d-9f08-7d786761c47b ls:10931s isR:false isF:true isM:false isN:false mc:0 ,null ,isUp:false ,vm:30
E/AndroidRuntime( 3304): java.lang.ArithmeticException: divide by zero
E/AndroidRuntime( 3304): 	at com.odehbros.flutter_file_downloader.core.DownloadTask$1.run(DownloadTask.java:74)
E/AndroidRuntime( 3304): 	at java.lang.Thread.run(Thread.java:923)

**Comment by coderXiezhiheng** [comment]
[√] Flutter (Channel stable, 3.7.11, on Microsoft Windows [版本 10.0.22621.1992], locale zh-CN)
    • Flutter version 3.7.11 on channel stable at D:\flutter_sdk\flutter_windows_3.7.11-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (4 months ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

**Comment by abdallah-odeh** [comment]
Hello @coderXiezhiheng 
Can you please share the download link you passed to the plugin

**Comment by abdallah-odeh** [comment]
Hello @coderXiezhiheng,

I added an assertion to throw an error to flutter incase that the download file size was zero,
please consider testing it out on the prerelease version `flutter_file_downloader: ^1.1.4-dev.1`

thanks in advance

**Comment by coderXiezhiheng** [comment]
![image](https://github.com/abdallah-odeh/flutter_file_downloader/assets/128438696/72409107-4c47-4469-a635-7457dab6ccb9)
After checking, it is indeed an exception caused by the file size being 0. Thank you for the fix .

**Comment by abdallah-odeh** [comment]
Great to hear that your issue is solved, thank you for helping in making this plugin better
