### ISSUE TITLE
downloadFile returns wrong FilePath with prefix "file: " 

### ISSUE THREAD

**Issue by plabon** [abdallah-odeh/flutter_file_downloader#20]
Version: 1.1.3
Device: Pixel 6
OS: Android 13

`FileDownloader.downloadFile()` function returns a File object with wrong file path(includes prefix `file:`). 

This is due to [this](https://github.com/abdallah-odeh/flutter_file_downloader/pull/19/commits/98f11143ab8f62a5b4efa0ac28a6fd27791dc793#:~:text=task.onDownloadCompleted(cursor.getString(cursor.getColumnIndex(DownloadManager.COLUMN_LOCAL_URI)))%3B) change. `DownloadManager.COLUMN_LOCAL_URI ` returns file path including "file://"

**Comment by abdallah-odeh** [comment]
Hello @plabon,

Thank you for profiling this issue, I'll check it and upload a fix shortly,
If this stops you please use the version `flutter_file_downloader: 1.1.2` unless you need the notifications management feature.

Thank you for helping in making this plugin better

**Comment by abdallah-odeh** [comment]
Hello @plabon,
I fixed the issue and uploaded a **Prerelease** version, 
I will be glad to hear from you about your case's results

please update your pub spec.yaml to `flutter_file_downloader: ^1.1.4-dev.1` to test it out.

Thanks in advance

**Comment by plabon** [comment]
Hey @abdallah-odeh,
Thanks for providing a fix quickly. I have tested the dev version and its working fine. 
You can release this fix. 

Thanks

**Comment by abdallah-odeh** [comment]
Hello @plabon, 

I will release it to production and let you know, thanks

**Comment by abdallah-odeh** [comment]
The version is now published on production `flutter_file_downloader: ^1.1.4`

please feel free to reopen this issue if you faced any further related issues
