### ISSUE TITLE
Special characters in FileName does not throw any error?

### ISSUE THREAD

**Issue by plabon** [abdallah-odeh/flutter_file_downloader#23]
If there is any special characters in file name the library does not throw or return any error, it just dies. 
For android special characters are: `[" * / : < > ? \\ / ]`

I don't expect to solve this issue from the library but at least I expect to throw an error with proper message. It took me some considerable amount of time to figure the issue.

Thanks in advance.

**Comment by abdallah-odeh** [comment]
Hello @plabon, can you please provide me with the download link & download file name?

I can't reproduce the issue (make the app die), it throws an exception in the native (unclear & unrelated exception), 
I tried:

- #.pdf -> Threw an exception
- k#.pdf -> Downloaded as k.pdf
- #k.pdf -> Threw an exception
- k#k.pdf -> Downloaded as k.pdf

Note that when it throws an exception the app keeps running without any issues

**Comment by abdallah-odeh** [comment]
Can you please try out the prerelease version `flutter_file_downloader: ^1.2.0-dev.2`

I could not reproduce the issue and force the app to die,

`DownloadManager` updates the downloaded file path and omits whatever characters after the not-allowed special character
also as I saw while debugging, it throws 2 different exceptions according to the provided special character
- `SecurityException("Unsupported path /storage/emulated/0/Download/o@k.pdf")`
- `SecurityException("java.io.IOException: Invalid file path /storage/emulated/0/Download/o/k.pdf")`

but in some other cases, it does not through an exception but the file sticks at 0% progress and it's status in the files **Queued**, also it changes the passed name to omit the special character with all characters after
e.g.: (**o#k.pdf**) Download manager changes it to be o.pdf

this issues are now solved in the new prerelease, please take sometime to try it on your use case and let me know the results

**Comment by abdallah-odeh** [comment]
Hello @plabon,
I will be publishing this fix on production this weekend,
I tested it out and works fine, please if you have any note, suggestions or unexpected behaviors let me know before this weekend to include in the production version.

thanks in advance.

**Comment by plabon** [comment]
Hey me again. I was looking at the changes. I have couple of observations:

- Why the name check part is removed from the `getExtension()` function? [here](https://github.com/abdallah-odeh/flutter_file_downloader/commit/73faf76fd380e699d7d6192e8cdcfdcd916cb2cc#diff-dd9b9ba67a73ebd37f3cf132b9e15270a91f3d483f06f522d86f50fbdc008ff9L143:~:text=%3D%20getName()%3B-,//%20%20%20%20%20%20%20%20String%20toCheck%20%3D%20name%3B,//%20%20%20%20%20%20%20%20%7D,-final%20String%5B%5D)

- Also the `getExtension()` function logic is not considering the query parms of download url. For example: `www.testtest.com/video/name.mp4?accesstoken=asgdgaskgdkhagskdg&userid=khkjhk.tyrb`

**Comment by abdallah-odeh** [comment]
Hello @plabon 
Thank you for opening my eyes on that, I didn't pay attention to the query params bug
Please if you have sometime your contribution is widely welcomed
I will work on it ASAP inshallah
Thank you again

**Comment by abdallah-odeh** [comment]
Hello again @plabon,
I have push a new commits to the branch [development](https://github.com/abdallah-odeh/flutter_file_downloader/tree/development)
please take sometime to view it and your comments are highly appreciated.

thank you for helping in improving this plugin
