### ISSUE TITLE
How to integrate with flutter_inappwebview?

### ISSUE THREAD

**Issue by mulfa8525** [abdallah-odeh/flutter_file_downloader#24]
Assalamualaikum, sir...
Can this plugin be integrated with flutter_inappwebview? If you need references, you can check this: https://gist.github.com/pichillilorenzo/ee74e103fdc324f761c5fde7b73bd430. And if you wish, what steps should I take?
Thank you for your best plugin

**Comment by mulfa8525** [comment]
And when i use your plugin, appears like this: 
![z3](https://github.com/abdallah-odeh/flutter_file_downloader/assets/150482505/7dc49f4e-61c0-4076-b35a-3b857d3223c5)

**Comment by abdallah-odeh** [comment]
Hello @mulfa8525,
which version are you using of `flutter_inappwebview`?
because the callback you are using deprecated when I used `flutter_inappwebview: ^5.8.0`

using the latest version `flutter_inappwebview: ^5.8.0` is possible of course, 
but by using their new download callback `onDownloadStartRequest` and passing the `downloadStartRequest.uri.toString()`

here is the full code of the example you provided

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_file_downloader/flutter_file_downloader.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:permission_handler/permission_handler.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Permission.storage.request();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late InAppWebViewController _webViewController;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('InAppWebView Example'),
        ),
        body: Container(
            child: Column(children: <Widget>[
          Expanded(
              child: InAppWebView(
            initialOptions: InAppWebViewGroupOptions(
              crossPlatform: InAppWebViewOptions(useOnDownloadStart: true),
            ),
            onWebViewCreated: (InAppWebViewController controller) {
              _webViewController = controller;
              _webViewController.loadUrl(
                  urlRequest: URLRequest(
                      url: Uri.parse('http://ovh.net/files/1Mio.dat')));
            },
            onDownloadStartRequest: (controller, downloadRequest) async {
              await FileDownloader.downloadFile(
                url: downloadRequest.url.toString(),
                name: 'TESTING',
                notificationType: NotificationType.all,
                downloadDestination: DownloadDestinations.publicDownloads,
                onProgress: (fileName, progress) {
                  debugPrint('FILE $fileName HAS PROGRESS $progress');
                },
                onDownloadCompleted: (path) {
                  debugPrint('FILE DOWNLOADED TO PATH: $path');
                },
                onDownloadError: (error) {
                  debugPrint('DOWNLOAD ERROR: $error');
                },
              );
            },
          ))
        ])),
      ),
    );
  }
}
```

**Comment by mulfa8525** [comment]
Hello, sir. Yes, right. I don't use downloadRequest. But does this snippet work, sir? I encountered a problem like this:
=====
E/MethodChannel#com.abdallah.libs/file_downloader(16491): Failed to handle method call
E/MethodChannel#com.abdallah.libs/file_downloader(16491): java.lang.StringIndexOutOfBoundsException: length=171; index=-1
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at java.lang.String.substring(String.java:2475)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at com.odehbros.flutter_file_downloader.core.DownloadTask.getExtension(DownloadTask.java:145)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at com.odehbros.flutter_file_downloader.core.DownloadTask.getDownloadedFileName(DownloadTask.java:151)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at com.odehbros.flutter_file_downloader.core.DownloadTask.startDownloading(DownloadTask.java:39)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onStartDownloadingFile(MethodCallHandlerImpl.java:238)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:68)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#com.abdallah.libs/file_downloader(16491): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
=====
I run it use AVD API 34. Thanks before.
![z7](https://github.com/abdallah-odeh/flutter_file_downloader/assets/150482505/8a2ba4df-8216-4ae4-9fd2-4aa3c688d73e)

**Comment by abdallah-odeh** [comment]
it works fine on my side, 
can you please provide me with your

- flutter doctor -v
- your `flutter_inappwebview: ^x.x.x` version
- your `flutter_file_downloader: ^x.x.x` version
- your testing device's android version

**Comment by abdallah-odeh** [comment]
here is a simulation of how it works on my side, please let me know if you've tried another button or file to download

I am using

- `flutter_file_downloader: ^1.1.4`
- `flutter_inappwebview: ^5.8.0`

https://github.com/abdallah-odeh/flutter_file_downloader/assets/68509938/5903bebe-cda8-4f44-ae97-2a11bf2792b1

**Comment by mulfa8525** [comment]
1. flutter doctor -v:
![1](https://github.com/abdallah-odeh/flutter_file_downloader/assets/150482505/6cbf05be-255b-4f97-acfa-431e8c4a00f1)
2. flutter_inappwebview: 6.0.0-beta.25
3. flutter_file_downloader: ^1.1.4
4. Nexus 5X API 34 (bottom right).
5. AndroidManifest.xml: 
![2](https://github.com/abdallah-odeh/flutter_file_downloader/assets/150482505/e01e2b9a-2c3b-42cc-8692-0cb10c240215)

**Comment by abdallah-odeh** [comment]
it seems that there is an issue with the production code from my side,

can you please try using the prerelease version `flutter_file_downloader: ^1.2.0-dev.3`

it's supposed to go live this week inshallah
give it a try and let me know the results

**Comment by mulfa8525** [comment]
![3](https://github.com/abdallah-odeh/flutter_file_downloader/assets/150482505/b012fad2-f04b-4626-96b4-2c1763a0439d)
The result is like this, sir. Try changing the URL to here: https://ditingali.com/dosen-gue-beranda/ > Click "Halaman Lain" > Click "Google Drive" > Click "download icon".

**Comment by abdallah-odeh** [comment]
I see that the issue with GoogleDrive links & such cloud storages don't provide the url path directly, instead they pass the document UUID in the queryparameters, 
this feature is actually not implemented, I will create a new issue to address it to keep a reminder to work on it

Clicked download link in GoogleDrive:
https://doc-10-b0-docs.googleusercontent.com/docs/securesc/907lkmgf5ks6qskgfsb6ig7ijirbbb6k/31s700q7g43ldeplqk8l18dgq7tr1tgk/1699729725000/11694911992450723259/14319665335375992075Z/1jBCYJsA_DWf2vFMJyGL0jKhH55adpjR8?e=download&uuid=b3f18fea-96ea-41f4-9473-edcf00a56e68

**Comment by mulfa8525** [comment]
Okay sir. This could be an opportunity for your plugin. Because lots of flutter_inappwebview users experience problems like this (you can check stackoverflow).
Hopefully it can be done as soon as possible, sir.

**Comment by mulfa8525** [comment]
One more, sir. Try changing the URL to: https://kaskeuangan.ditingali.com/. After login: Click 3 BARS > MASUK > Shift the table to the right > AKSI > DOWNLOAD ICON.

**Comment by abdallah-odeh** [comment]
I will do my best to get it done this week

The last case falls under the same issue when downloading from GoogleDrive
I followed your instructions and the download link was: `https://kaskeuangan.ditingali.com/admin/kas_masuk_download.php?id=22`, the file is retrieved by passing it's id and the URL does not represent the file's path on the server

**Comment by abdallah-odeh** [comment]
Hello @mulfa8525 
Unfortunately, it seems that I will not be able to implement downloading files from GoogleDrive, because they have their own APIs & services that need to be enabled per project
also I am trying to keep this plugin libraries-free to avoid dependencies conflicts & GoogleDrive download requires their SDKs to be imported

A new changes will be published soon, such as reading file content, which will solve an issue of yours; in the current version the file in https://kaskeuangan.ditingali.com/admin/kas_masuk_download.php?id=22 cannot be downloaded, in the new version it does

I will keep you updated about any updates in your issues
thank you for understanding & helping in improving this plugin

Please feel free to reopen this issue or create a new one if you have further notes
