### ISSUE TITLE
Add support to read file content from URL and download it

### ISSUE THREAD

**Issue by abdallah-odeh** [abdallah-odeh/flutter_file_downloader#25]
GoogleDrive & similar cloud storage does not provide the download link path, 
instead, the provide a URL with the document id in the DB
this leads to errors in current code `flutter_file_downloader: ^1.1.4`+

To be implemented; to be able to read file content from the passed URL, get file name & extension from the URL content & save the file in device's storage

Sample GoogleDrive link: 
https://doc-08-44-docs.googleusercontent.com/docs/securesc/907lkmgf5ks6qskgfsb6ig7ijirbbb6k/0kljd16dp4ivsftp9g58chgleuv6tsl6/1699730700000/03742505243896446090/14319665335375992075Z/1z-ENB2T-xQne58YldxjNU3juqwWzwBMl?e=download&uuid=1d970c35-341f-4283-b797-f0e9d73d8212&nonce=voj3pgdjiroba&user=14319665335375992075Z&hash=15e3ihnlp3279996pr476i87funmddoo

related issues: #24

**Comment by mulfa8525** [comment]
Hello,
Is there any progress, sir?

**Comment by abdallah-odeh** [comment]
Hello @mulfa8525,
Hopefully, I will be able to deploy a dev version at the end of January
It's taking more than expected but nearly the whole code needs to be refactored & I'm a bit busy nowadays 
Thank you for understanding 
I will be posting updates in this thread to keep you & anyone interested updated inshallah

**Comment by mulfa8525** [comment]
Okay, sir.
Your plugin is amazing.

**Comment by mulfa8525** [comment]
I'am waiting for good news from you, because this is not easy.

**Comment by abdallah-odeh** [comment]
Hello @mulfa8525 
I am really sorry but I been very busy last couple weeks, I achieved a good progress but still, some of the main functionality is not implemented such as progress notifications, changing file name after download and choose download path
This has to be implemented from zero, so maybe I will upload a dev version with very basic functionality of the currently available and improve it during the days

I am doing my best to deploy a version with the new download technique because it solves a lot of issues
but unfortunately I can't promise any soon date
if anything come up I will let you know

thank you for understanding

**Comment by abdallah-odeh** [comment]
🚨 Breaking news!! 🚨
hello @mulfa8525 
A new version has been deployed for testing `flutter_file_downloader: ^2.0.0-dev.1`, this version has the ability to download a file from content as requested along with other rich features, 
please see the [CHANGELOG](https://pub.dev/packages/flutter_file_downloader/versions/2.0.0-dev.1/changelog#200-dev1) for more details

It would be highly appreciated to test it out before rolling it to production
thanks in advance

**Comment by abdallah-odeh** [comment]
Hello @mulfa8525  
A new version has been released to production, `flutter_file_downloader: ^2.0.0`
please test it out and if you found any issue or enhancement let me know by creating a new issue
Closing this issue as completed
