### ISSUE TITLE
does it Download files to Downloads Directory in android 13 ?

### ISSUE THREAD

**Issue by dpr24** [abdallah-odeh/flutter_file_downloader#32]
does it Download files to Downloads Directory in android 13?

**Comment by abdallah-odeh** [comment]
yes sure, are facing any issue with it?

**Comment by abdallah-odeh** [comment]
please if you have any other question or having an issue with the plugin feel free to comment on this issue or open a new one

**Comment by varunHoneyComb** [comment]
i am facing issue i am am downloading video if there are 10 video all being dowloaded but some of them are no playing error cant play this video

**Comment by abdallah-odeh** [comment]
Hello @varunHoneyComb 
can you please provide me with the URLs that don't work?
I tried to download multiple videos and they work fine after downloading
