### ISSUE TITLE
There is also a save path, which should be optionally passed in by the developer.

### ISSUE THREAD

**Issue by xiongzhaoxu** [abdallah-odeh/flutter_file_downloader#36]
There is also a save path, which should be optionally passed in by the developer.

**Comment by abdallah-odeh** [comment]
Providing a custom path is not supported, because the user cannot write anywhere he wants which may lead to instability of the plugin
thus, you can choose where you would like to save the file, `app temporary directory` or `public downloads`

**Comment by xiongzhaoxu** [comment]
> Providing a custom path is not supported, because the user cannot write anywhere he wants (this requires different app permissions or some paths are not available for you to write in) which may lead to instability of the plugin thus, you can choose where you would like to save the file, `app temporary directory` or `public downloads`

OK

**Comment by xiongzhaoxu** [comment]
> Providing a custom path is not supported, because the user cannot write anywhere he wants (this requires different app permissions or some paths are not available for you to write in) which may lead to instability of the plugin thus, you can choose where you would like to save the file, `app temporary directory` or `public downloads`

In Android 13, do I need to apply for permission for the publicDownloads download path?

**Comment by abdallah-odeh** [comment]
If your `targetSdkVersion` is set to 33+ (android 13+) then no, you don't need to add any permissions

otherwise you do need:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`

Note that in both cases the plugin needs the permission:
`<uses-permission android:name="android.permission.INTERNET"/>` but it's already added in the plugin itself and works fine because it's not considered as sensitive permission

**Comment by xiongzhaoxu** [comment]
> If your `targetSdkVersion` is set to 33+ (android 13+) then no, you don't need to add any permissions
> 
> otherwise you do need: `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
> 
> Note that in both cases the plugin needs the permission: `<uses-permission android:name="android.permission.INTERNET"/>` but it's already added in the plugin itself and works fine because it's not considered as sensitive permission

I tested targetSdkVersion 33 (android 13) here, and it stopped moving when downloading. Everything below 33 is normal.

**Comment by xiongzhaoxu** [comment]
> If your `targetSdkVersion` is set to 33+ (android 13+) then no, you don't need to add any permissions
> 
> otherwise you do need: `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
> 
> Note that in both cases the plugin needs the permission: `<uses-permission android:name="android.permission.INTERNET"/>` but it's already added in the plugin itself and works fine because it's not considered as sensitive permission

I tested targetSdkVersion 33 (android 13) here, and it stopped moving when downloading. Everything below 33 is normal. To be precise, I set targetSdkVersion to 33, compiled the APK and installed it on an android 13 device, but the download failed. All the permissions mentioned above have been added

**Comment by abdallah-odeh** [comment]
Have you tried the example project in the plugin? I tested it out and works perfectly

what is the exception returned in `onDownloadFailed`?
It would be great if you can provide me with a sample project to reproduce the issue because I tried it on same configurations you mentioned and works as expected

**Comment by xiongzhaoxu** [comment]
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_file_downloader/flutter_file_downloader.dart';
import 'package:progress_dialog_null_safe/progress_dialog_null_safe.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  //定义apk的名称，与下载进度dialog
  String apkName = 'new_app.apk';
  String apkUrl = "https://static.yjzf.com/app_version/2024-01-18/com.yjyz.uc_2.30.1_ujuz_app.apk";
  late ProgressDialog pr;

  @override
  void initState() {
    super.initState();
    pr = ProgressDialog(context,
        type: ProgressDialogType.download,
        isDismissible: false,
        showLogs: true);
    pr.style(
        message: '下载中请稍后...',
        borderRadius: 10.0,
        backgroundColor: Colors.white,
        progressWidget: Container(
            padding: const EdgeInsets.all(8.0),
            child: const CircularProgressIndicator()),
        elevation: 10.0,
        insetAnimCurve: Curves.easeInOut,
        progress: 0.0,
        //textDirection: TextDirection.rtl,
        maxProgress: 100.0,
        progressTextStyle: const TextStyle(
            color: Colors.black, fontSize: 12.0, fontWeight: FontWeight.w400),
        messageTextStyle: const TextStyle(
            color: Colors.black, fontSize: 16.0, fontWeight: FontWeight.w600));
  }

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            //
            CupertinoButton(
                pressedOpacity: 0.3,
                padding:
                    const EdgeInsetsDirectional.only(end: 16, top: 0),
                child: const Text(
                  'downloader',
                  style: TextStyle(
                      color: Color(0xff474df0), fontSize: 16),
                ),
                onPressed: () async {
                  await pr.show();
                  print("is downloader");
                    //   //You can download a single file
                    FileDownloader.downloadFile(
                        url: apkUrl,
                        name: apkName, //(optional)
                        downloadDestination: DownloadDestinations.appFiles,
                        onProgress: (String? fileName, double progress) {
                          print('${fileName} FILE fileName HAS PROGRESS $progress');
                          pr.update(progress: progress);
                        },
                        onDownloadCompleted: (String path) async {
                          if (pr.isShowing()) {
                            pr.hide();
                          }
                          print('FILE DOWNLOADED TO PATH: $path');
                        },
                        onDownloadError: (String error) {
                          if (pr.isShowing()) {
                            pr.hide();
                          }
                          print('DOWNLOAD ERROR: $error');
                        });
                },
              )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`


`name: apk_install
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_file_downloader: ^1.2.1
  progress_dialog_null_safe: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

`Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (10 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5`

**Comment by xiongzhaoxu** [comment]
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_file_downloader/flutter_file_downloader.dart';
import 'package:progress_dialog_null_safe/progress_dialog_null_safe.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  //定义apk的名称，与下载进度dialog
  String apkName = 'new_app.apk';
  String apkUrl = "https://static.yjzf.com/app_version/2024-01-18/com.yjyz.uc_2.30.1_ujuz_app.apk";
  late ProgressDialog pr;

  @override
  void initState() {
    super.initState();
    pr = ProgressDialog(context,
        type: ProgressDialogType.download,
        isDismissible: false,
        showLogs: true);
    pr.style(
        message: '下载中请稍后...',
        borderRadius: 10.0,
        backgroundColor: Colors.white,
        progressWidget: Container(
            padding: const EdgeInsets.all(8.0),
            child: const CircularProgressIndicator()),
        elevation: 10.0,
        insetAnimCurve: Curves.easeInOut,
        progress: 0.0,
        //textDirection: TextDirection.rtl,
        maxProgress: 100.0,
        progressTextStyle: const TextStyle(
            color: Colors.black, fontSize: 12.0, fontWeight: FontWeight.w400),
        messageTextStyle: const TextStyle(
            color: Colors.black, fontSize: 16.0, fontWeight: FontWeight.w600));
  }

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            //
            CupertinoButton(
                pressedOpacity: 0.3,
                padding:
                    const EdgeInsetsDirectional.only(end: 16, top: 0),
                child: const Text(
                  'downloader',
                  style: TextStyle(
                      color: Color(0xff474df0), fontSize: 16),
                ),
                onPressed: () async {
                  await pr.show();
                  print("is downloader");
                    //   //You can download a single file
                    FileDownloader.downloadFile(
                        url: apkUrl,
                        name: apkName, //(optional)
                        downloadDestination: DownloadDestinations.appFiles,
                        onProgress: (String? fileName, double progress) {
                          print('${fileName} FILE fileName HAS PROGRESS $progress');
                          pr.update(progress: progress);
                        },
                        onDownloadCompleted: (String path) async {
                          if (pr.isShowing()) {
                            pr.hide();
                          }
                          print('FILE DOWNLOADED TO PATH: $path');
                        },
                        onDownloadError: (String error) {
                          if (pr.isShowing()) {
                            pr.hide();
                          }
                          print('DOWNLOAD ERROR: $error');
                        });
                },
              )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by xiongzhaoxu** [comment]
name: apk_install
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_file_downloader: ^1.2.1
  progress_dialog_null_safe: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

**Comment by xiongzhaoxu** [comment]
Or the complete project, https://mp-e47607e8-56f5-4e29-91d2-f4c2f4cf8ec9.cdn.bspapp.com/apk_install.zip

**Comment by abdallah-odeh** [comment]
I tried your code & source code! they both worked and I got the apk downloaded on the emulator

what is the exception returned in `onDownloadFailed`?

**Comment by xiongzhaoxu** [comment]
![iShot_2024-01-30_09 30 39](https://github.com/abdallah-odeh/flutter_file_downloader/assets/6897602/1c8917b4-7905-4298-8de0-8927abe4cc99)
I run the code and this output is NULL

**Comment by abdallah-odeh** [comment]
Hello @xiongzhaoxu 
I fixed the redundant call for `onProgress` callback,
please if you have any other issue feel free to file a new issue or reopen this one

thank you for helping in improving this plugin
