### ISSUE TITLE
Can't download with HTTPS POST request

### ISSUE THREAD

**Issue by 1teapot** [abdallah-odeh/flutter_file_downloader#38]
I know that normally we download via HTTP GET request, but the api I'm using is required to send POST request with payload body or sometime form data, and header. Is there a way to achieve that?

**Comment by abdallah-odeh** [comment]
Hello @1teapot 
Unfortunately, this is currently not implemented

will see if it's possible in the future, I am already refactoring the code to support other features requested by users,
so will see if this is applicable in the new code

**Comment by hadi7khan** [comment]
@1teapot What alternative you used? Currently facing same issue.

**Comment by abdallah-odeh** [comment]
Hello Guys @abdallah-odeh & @1teapot 
do you have any URL that I can try to download a file via POST request?
I am currently working on this feature & want to test it out

thank you for cooperation

**Comment by abdallah-odeh** [comment]
🚨 Breaking news!! 🚨
A new version has been deployed for testing `flutter_file_downloader: ^2.0.0-dev.1`, this version has the ability to download files over POST request

It would be highly appreciated to test it out before rolling it to production
thanks in advance

**Comment by abdallah-odeh** [comment]
Hello @1teapot & @hadi7khan 
is there any updates on this? did you try the prerelease version on your use case?
I want to roll this version into production but I need your confirmation as it works as needed

thanks in advance

**Comment by abdallah-odeh** [comment]
Hello @1teapot & @hadi7khan 
A new version has been released to production, `flutter_file_downloader: ^2.0.0`
please test it out and if you found any issue or enhancement let me know by creating a new issue
Closing this issue as completed
