### ISSUE TITLE
[Feature request] Download content generated by the app

### ISSUE THREAD

**Issue by pryshrm** [abdallah-odeh/flutter_file_downloader#4]
It would be great if there is a way to provide data (such as a String or int[] or something) created by the app itself instead of a url. So that the user can save that data as a file. Like an "export to csv" kind of functionality.

**Comment by abdallah-odeh** [comment]
@pryshrm that would be a good feature to add, will be working on it in the next few weeks,
I will keep you updated

**Comment by abdallah-odeh** [comment]
Hello @pryshrm 
The feature you requested is not considered as a `Download` feature as downloading is only supported from cloud files
so generated files can only be saved any other file, and it's simple actually 😅
you can do it by writing `await File(desiredDestinationPath).writeAsBytes(your data to save);`
Closing this issue as nothing left to do 😅
if there is something I can do please don't hesitate reopening the issue

**Comment by abdallah-odeh** [comment]
Hello @pryshrm 
A new version has been released to production, `flutter_file_downloader: ^2.0.0`
please test it out and if you found any issue or enhancement let me know by creating a new issue
Closing this issue as completed
