### ISSUE TITLE
Error Missing permission, see the log for more info

### ISSUE THREAD

**Issue by mnaufalhamdani** [abdallah-odeh/flutter_file_downloader#41]
![Screenshot 2024-03-07 at 15 18 56](https://github.com/abdallah-odeh/flutter_file_downloader/assets/15699628/c0e55423-04ac-411b-b86e-3c92d24709e8)
![Screenshot 2024-03-07 at 15 26 39](https://github.com/abdallah-odeh/flutter_file_downloader/assets/15699628/869410c5-3f3a-4a84-b6ba-fd48c3e5b503)

how do I fix this, I have added permission without notification in AndroidManifest.xml, but it still doesn't work. I use getX and the code to download I put it in the controller

**Comment by itsSagarBro** [comment]
Same error.

**Comment by abdallah-odeh** [comment]
Did you guys did `flutter clean` & rebuild after adding the permission?
because it's not applied when you do a `hot refresh`

**Comment by itsSagarBro** [comment]
@abdallah-odeh Thanks for the reply, It gave an error because I wasn't requesting storage permission, on an older Android version. Not it is fixed.

**Comment by mnaufalhamdani** [comment]
@abdallah-odeh thank you for your comment, I had to add storage permissions for it to run, that worked. I skipped the code because in the tutorial on pub.dev there is no need to add storage permissions.

**Comment by abdallah-odeh** [comment]
@mnaufalhamdani the storage permission is required or optional depending on your `targetSdkVersion`, can you please tell me what is the value you have for `targetSdkVersion`?

**Comment by mnaufalhamdani** [comment]
I'm using Target SDK 29
