### ISSUE TITLE
How can I add a folder inside the default downloads folder?

### ISSUE THREAD

**Issue by raffyxyz** [abdallah-odeh/flutter_file_downloader#43]
I want to add a folder inside the downloads directory when downloading for example "emulated/0/downloads/my_folder" is this possible? I'm just new to flutter  so any help or guides is greatly appreciated.

**Comment by abdallah-odeh** [comment]
Hello @raffyxyz, I quickly tested that on the code I refactored & it works!
sadly I'm a bit busy nowadays, I will do my best to deploy a version of the refactored code before May as it solves a good amount of issues on the repo

I will keep you updated once this is released

**Comment by raffyxyz** [comment]
No worries, take your time.

**Comment by abdallah-odeh** [comment]
🚨 Breaking news!! 🚨
hello @raffyxyz, 
A new version has been deployed for testing `flutter_file_downloader: ^2.0.0-dev.1`, this version has the ability to create sub directories as you requested

It would be highly appreciated to test it out before rolling it to production
thanks in advance

**Comment by abdallah-odeh** [comment]
Hello @raffyxyz,
did you try this prerelease version? did it work as needed?
I want to roll this version into production but I want your confirmation first

thanks in advance

**Comment by raffyxyz** [comment]
Hey @abdallah-odeh, I've been busy with a lot of stuff. I'll try your updated package this weekend.

**Comment by raffyxyz** [comment]
Hey, @abdallah-odeh the subpath works fine but there's a bug in the download progress. It doesn't start from 0% It will begin randomly and then go back to zero to a hundred.

**Comment by abdallah-odeh** [comment]
Did you try to download a large file? because DownloadManager is pretty fast in downloading 😅, so when downloading a large file you can track download clearly

It might be an enhancement to set the progress to 0% right away when download task is issued, I will do it in the next version inshallah

**Comment by abdallah-odeh** [comment]
Closing this issue as completed, please if you have any other issues feel free to open a new one
