### ISSUE TITLE
[SDK 34] One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by bebaoboy** [abdallah-odeh/flutter_file_downloader#44]
**Describe the bug**
I got this error when building my flutter app on Android 14 (SDK 34), saying:
"One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts."

After that, I cannot download any files using the library.
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): Failed to handle method call
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at com.odehbros.flutter_file_downloader.core.DownloadTask.startDownloading(DownloadTask.java:81)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onStartDownloadingFile(MethodCallHandlerImpl.java:246)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:79)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at android.os.Looper.loopOnce(Looper.java:222)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at android.os.Looper.loop(Looper.java:314)
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at android.app.ActivityThread.main(ActivityThread.java:8670)
...
E/MethodChannel#com.abdallah.libs/file_downloader( 9597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
I/flutter ( 9597): downloadFile error: PlatformException(error, Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
I/flutter ( 9597): 	at com.odehbros.flutter_file_downloader.core.DownloadTask.startDownloading(DownloadTask.java:81)
I/flutter ( 9597): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onStartDownloadingFile(MethodCallHandlerImpl.java:246)
I/flutter ( 9597): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:79)
I/flutter ( 9597): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
I/flutter ( 9597): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
I/flutter ( 9597): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter ( 9597): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter ( 9597): 	at android.os.Handler.handleCallback(Handler.java:958)
I/flutter ( 9597): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter ( 9597): 	at android.os.Looper.loopOnce(Looper.java:222)
I/flutter ( 9597): 	at android.os.Looper.loop(Looper.java:314)
I/flutter ( 9597): 	at android.app.ActivityThread.main(ActivityThread.java:8670)

**To Reproduce**
-Been using the library for some weeks, running normally on older Android devices.
-Build and run like a normal flutter project.

**Expected behavior**
No error on device with Android SDK above 34.

**Screenshots**
![image](https://github.com/abdallah-odeh/flutter_file_downloader/assets/74720131/49841b31-0c48-4f59-ac4f-6d0eb3c555e6)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11T
 - OS: Android 14
 - SDK Version 34
 - Plugin version: flutter_file_downloader: ^1.2.1 (latest)

**Additional context**
Stack trace:
E/GeneratedPluginRegistrant( 9597): Error registering plugin flutter_file_downloader, com.odehbros.flutter_file_downloader.FlutterFileDownloaderPlugin
E/GeneratedPluginRegistrant( 9597): java.lang.SecurityException: com.iotecksolutions.todoapp: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/GeneratedPluginRegistrant( 9597): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/GeneratedPluginRegistrant( 9597): 	at android.os.Parcel.createException(Parcel.java:3041)
E/GeneratedPluginRegistrant( 9597): 	at android.os.Parcel.readException(Parcel.java:3024)
E/GeneratedPluginRegistrant( 9597): 	at android.os.Parcel.readException(Parcel.java:2966)
E/GeneratedPluginRegistrant( 9597): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6193)
E/GeneratedPluginRegistrant( 9597): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
E/GeneratedPluginRegistrant( 9597): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
E/GeneratedPluginRegistrant( 9597): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
E/GeneratedPluginRegistrant( 9597): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
E/GeneratedPluginRegistrant( 9597): 	at com.odehbros.flutter_file_downloader.FlutterFileDownloaderPlugin.bindForegroundService(FlutterFileDownloaderPlugin.java:101)
E/GeneratedPluginRegistrant( 9597): 	at com.odehbros.flutter_file_downloader.FlutterFileDownloaderPlugin.onAttachedToEngine(FlutterFileDownloaderPlugin.java:49)
E/GeneratedPluginRegistrant( 9597): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:147)
E/GeneratedPluginRegistrant( 9597): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:74)
E/GeneratedPluginRegistrant( 9597): 	at java.lang.reflect.Method.invoke(Native Method)
E/GeneratedPluginRegistrant( 9597): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/GeneratedPluginRegistrant( 9597): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:385)
E/GeneratedPluginRegistrant( 9597): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:287)
E/GeneratedPluginRegistrant( 9597): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:268)
E/GeneratedPluginRegistrant( 9597): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:248)
E/GeneratedPluginRegistrant( 9597): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:168)

Please kindly fix as soon as possible 😢😢😢. Thank you so much!
P.S. : Idk but I found the same issue in this link [https://github.com/joltup/rn-fetch-blob/issues/866](url), related to the new Android policy...

**Comment by abdallah-odeh** [comment]
Hello @bebaoboy 
I had plans to test it out on the new android version, v14
I quickly looked into the issue link you provided, the solution seems to be easy
I'll deploy an update to fix it tonight inshallah

thanks for helping in improving this plugin

**Comment by bebaoboy** [comment]
I'll try that really soon and tell you! Thanks for the reply

**Comment by bebaoboy** [comment]
> can you please test it out on the version `flutter_file_downloader: ^1.2.2-dev.1` and tell me the results

So i did use this version on my android 14 and it worked!!!

![Screenshot_2024-04-08-23-46-22-041_com.iotecksolutions.todoapp.jpg](https://github.com/abdallah-odeh/flutter_file_downloader/assets/74720131/caa498c2-2cc1-4a13-adc5-53cfdb53ec1d)

**Comment by abdallah-odeh** [comment]
Sounds great, I will close this issue & promote this version to production
please if you found any other issue or have a suggestion feel free to open a new issue on reopen this one

thanks for helping in improving this plugin
