### ISSUE TITLE
IS THIS WORKED ON ANDROID 13 or LATER??

### ISSUE THREAD

**Issue by DeepakYiron** [abdallah-odeh/flutter_file_downloader#51]
i am working on downloading and save file in device storage .this work fine in android 13 and later,, I just  want to confirm is this work correctly without MANAGE_EXTERNAL_STORAGE permission ????

**Comment by abdallah-odeh** [comment]
Hello @DeepakYiron, yes it works fine on both android 13 & 14 without any permissions
did you try the sample code and face an issue?

**Comment by DeepakYiron** [comment]
Yes sir,  I have used this package and working fine bht sometime it will not work as expected in Android 14 ...worked on all version emulator but gives error on real  device.


I have screenshot of error please check ,and please suggest me how to resolve this.




Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by abdallah-odeh** [comment]
Can you please try to use the prerelease version `flutter_file_downloader: ^2.0.0-dev.1`, it solves an issue about registering the completer broadcast

Or it would be better to provide me with a screenshot from the log

**Comment by DeepakYiron** [comment]
Yes sure, i will try  and let you know tomorrow, thank you so much for update

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by abdallah-odeh** [comment]
You are most welcome, I hope it works well and if it did not, I'll be glad to help

**Comment by DeepakYiron** [comment]
Good morning Brother

I have updated to pre release version as you mentioned above .It's amazingly working fine ..thank you so much for your support. You save my efforts. Should I use use this version for my app release ??

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DeepakYiron** [comment]
I have capture some screenshot of error in VERSION 1.2.1 only in case of Android 14


Please check this may help you to resolve this bug on 1.2.1 version. or might be i was doing something wrong.




Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by abdallah-odeh** [comment]
Hello @DeepakYiron,

yes, surely you can, the new prerelease version adds some features that might not be stable such as 

1. download a file to a subdirectory
2. download a file via POST request
З. save base64 content to Downloads/ directory

and if you don't use any of these you will not face any issues inshallah
but if you any of them you **might** find issues 

if you face any issue please let me know so I can fix it
I am waiting to these features requesters to approve these changes according to their use cases

**Comment by DeepakYiron** [comment]
Ok thanks for update brother .
I just using package to download file and save into download folder..

Thank you so much.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by abdallah-odeh** [comment]
You are most welcome,
Please feel free to open new issue if face any problems

**Comment by DeepakYiron** [comment]
Sure ,thanks a lot

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
