### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by jaganath1991** [abdallah-odeh/flutter_file_downloader#52]
Hi,

i am using flutter_file_downloader: ^2.0.0 and its working fine and in same project i am using geolocator: ^12.0.0, in that time if i use the geolocator permission  for handle the permission application crashed in android API level 34. but if i use flutter_file_downloader 1.1.0+1 its working fine in android API level 33. So kindly check that issue.

**Comment by abdallah-odeh** [comment]
Hello @jaganath1991,
I'll test it out this weekend and tell you the results inshallah

**Comment by jaganath1991** [comment]
Hi @abdallah-odeh 

Are you test it?  kindly let me know if any solution are you getting.

**Comment by abdallah-odeh** [comment]
Hello @jaganath1991, sorry for the late response!
Can you please provide me with a minimal sample code to reproduce the issue? cuz I don't see any relation between both plugins
Location & Downloader, don't see where they cross

I tried the following code
```
 void getPermission()async  {
   final permission = await Geolocator.requestPermission();
   print('Geolocator permission is $permission');

   final file = await FileDownloader.downloadFile(url: 'https://tinypng.com/images/social/developer-api.jpg');
   print('File is $file');
  }
```

and I got in the console:
```
I/flutter (13691): Geolocator permission is LocationPermission.whileInUse
I/flutter (13691): File is File: '/storage/emulated/0/Download/developer-api.jpg'
```

**Comment by jaganath1991** [comment]
I/System.out(15494): PERMISSION android.permission.ACCESS_FINE_LOCATION
I/System.out(15494): PERMISSION android.permission.ACCESS_COARSE_LOCATION
D/AndroidRuntime(15494): Shutting down VM
E/AndroidRuntime(15494): FATAL EXCEPTION: main
E/AndroidRuntime(15494): Process: com.vscl.varanasipass, PID: 15494
E/AndroidRuntime(15494): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=109, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.vscl.varanasipass/com.vscl.varanasipass.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
E/AndroidRuntime(15494): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:6153)
E/AndroidRuntime(15494): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6192)
E/AndroidRuntime(15494): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(15494): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(15494): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime(15494): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/AndroidRuntime(15494): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2853)
E/AndroidRuntime(15494): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime(15494): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(15494): 	at android.os.Looper.loop(Looper.java:328)
E/AndroidRuntime(15494): 	at android.app.ActivityThread.main(ActivityThread.java:9220)
E/AndroidRuntime(15494): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15494): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
E/AndroidRuntime(15494): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(15494): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
E/AndroidRuntime(15494): 	at com.odehbros.flutter_file_downloader.permissions.PermissionHandler.onRequestPermissionsResult(PermissionHandler.java:87)
E/AndroidRuntime(15494): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:746)
E/AndroidRuntime(15494): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:405)
E/AndroidRuntime(15494): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:805)
E/AndroidRuntime(15494): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:908)
E/AndroidRuntime(15494): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:9484)
E/AndroidRuntime(15494): 	at android.app.Activity.dispatchActivityResult(Activity.java:9342)
E/AndroidRuntime(15494): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:6146)
E/AndroidRuntime(15494): 	... 13 more
I/Process (15494): Sending signal. PID: 15494 SIG: 9

Actually i am getting this error if you want then i'll share a project also. If i try to access the location or deny the location then the application crashed. and thank you for you response.  i really apricated.

**Comment by abdallah-odeh** [comment]
Can you please share the APIs you call from both libraries, or at least the method you call when this exception appear

**Comment by abdallah-odeh** [comment]
Oh, I think i got the cause, we both use the same permission request code!!
so when you request a permission using `geolocator` the plugin  `flutter_file_downloader` also catches the permission status change event and tries to do it's work, but it throws a fatal exception
I will deploy a fix tomorrow morning inshallah

thank you so much for catching such a bug!

**Comment by abdallah-odeh** [comment]
Hello @jaganath1991 
I've deployed a new prerelease version `flutter_file_downloader: ^2.0.1-dev.1`
please try it out and tell me if it works fine to roll it to production

thx

**Comment by jaganath1991** [comment]
Thanks @abdallah-odeh now its working fine. I really appreciate your work and defecation.

**Comment by abdallah-odeh** [comment]
Well, that is great to hear, I'll publish this version to production and let you know, 
until then, please feel free to reopen this issue or file a new one
