### ISSUE TITLE
endless loop in background

### ISSUE THREAD

**Issue by baali-boudjemaa** [abdallah-odeh/flutter_file_downloader#53]
i noticed that when i  finished downloading a file , the FileDownloader keep print  that line in background 
I/System.out(26333): Download ID: 9694, bytesTotal: -1, bytesDownloaded: 0 

<img width="461" alt="downmpad" src="https://github.com/user-attachments/assets/46156e6d-bfac-4aae-9612-5aea9070896e">

**Comment by abdallah-odeh** [comment]
Hello @baali-boudjemaa, sorry for the late respond
are you sure that the file has been downloaded? because according to the log, the file size could not be retrieved!
also can you please provide my with the link you requested to download

**Comment by baali-boudjemaa** [comment]
hi @abdallah-odeh  Sorry, after checking, I found that it is a link to a file that does not exist on the server

**Comment by abdallah-odeh** [comment]
No worries, It's better to clear that issue anyway.
thanks for reporting.

Closing this issue and creating a related PR
