### ISSUE TITLE
Support for custom dirPaths

### ISSUE THREAD

**Issue by AdamRiedl** [abdallah-odeh/flutter_file_downloader#61]
Hi great package. Worked like a charm but I have a big problem with it. I cannot set custom dirPath. In my app the app itself is downloading some configs from server. So i need for those files to be in private dir. But if i set the subPath to anything there is a prefix for /storage/emulated/0/Download/Directory and so on (Public storage), which is totally fine for any kind of User request for download but for anything more secure i don't see any way.
Thanks.

**Comment by abdallah-odeh** [comment]
Hello @AdamRiedl, 
Downloading files to any path to android is a bit complicated, but we currently support two directories you can download files to either **Downloads/** dir or Local app files which the user cannot easily access, 

this example is mentioned in the documentation
```
FileDownloader.downloadFile(
    url: url.text.trim(),
    name: name.text.trim(),
    downloadDestination: DownloadDestinations.appFiles, //this will download the files in a private directory
);
```

did you give it a shot?

**Comment by AdamRiedl** [comment]
Okay i will give it a shot and let you know. Thanks for the quick answer.

**Comment by AdamRiedl** [comment]
It indeed is saving the file into App files so the issue is done. Thank you.
